# Generated by Django 6.0.3 on 2026-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attack_type', models.CharField(max_length=100)),
                ('source_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('confidence', models.FloatField()),
                ('threat_summary', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=20)),
            ],
        ),
    ]
